version: "3.9"
services:
  db:
    image: timescale/timescaledb:latest-pg14
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=onboardpi
    volumes:
      - /var/lib/onboardpi/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
  web:
    build: ./web
    restart: always
    ports: 
      - 8080:8080
    volumes: 
      - /var/lib/onboardpi/data:/var/lib/onboardpi/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
      - POSTGRES_DB=onboardpi
      - SETTINGS_DIR=/var/lib/onboardpi/data
    depends_on:
      - db
  obd:
    build: ./obd
    restart: always
    privileged: true
    ports: 
      - 60000:60000
    volumes:
      - /var/lib/onboardpi/data:/var/lib/onboardpi/data:ro
      - /dev:/dev
      - /etc/localtime:/etc/localtime:ro
      # - /home/pi/.openauto/config:/home/pi/.openauto/config:ro
    environment:
      - SETTINGS_DIR=/var/lib/onboardpi/data
      - OAP_HOST=172.17.0.1
